yarn add react-native-reanimated
yarn add react-native-gesture-handler
yarn add react-native-screens
yarn add react-native-safe-area-context
yarn add react-native-dotenv
yarn add react-native-vector-icons
yarn add react-native-splash-screen
yarn add react-native-linear-gradient
yarn add react-native-skeleton-placeholder
yarn add react-native-svg-transformer
yarn add react-native-toast-message
yarn add react-native-image-picker
yarn add react-native-date-picker
yarn add react-native-paper
yarn add react-native-restart
yarn add react-native-svg
yarn add react-redux
yarn add redux-persist
yarn add redux-saga
yarn add react-i18next
yarn add @react-navigation/native
yarn add @react-navigation/native-stack
yarn add @react-navigation/drawer
yarn add @react-navigation/bottom-tabs
yarn add @gorhom/bottom-sheet
yarn add @react-native-async-storage/async-storage
yarn add @react-native-community/checkbox
yarn add @react-native-community/netinfo
yarn add @react-native-masked-view/masked-view
yarn add @tanstack/react-query
yarn add @reduxjs/toolkit
yarn add moment
yarn add socket.io-client
yarn add i18next
yarn add axios
yarn add formik
yarn add yup