npm install react-native-reanimated
npm install react-native-gesture-handler
npm install react-native-screens
npm install react-native-safe-area-context
npm install react-native-dotenv
npm install react-native-vector-icons
npm install react-native-splash-screen
npm install react-redux
npm install react-i18next
npm install @react-navigation/native
npm install @react-navigation/native-stack
npm install @react-navigation/drawer
npm install @react-navigation/bottom-tabs
npm install @gorhom/bottom-sheet
npm install @react-native-async-storage/async-storage
npm install @react-native-community/checkbox
npm install @react-native-masked-view/masked-view
npm install @tanstack/react-query
npm install @reduxjs/toolkit
npm install moment
npm install socket.io-client
npm install i18next
