yarn add react-native-reanimated
yarn add react-native-gesture-handler
yarn add react-native-safe-area-context
yarn add react-native-screens
yarn add react-native-bootsplash
yarn add react-native-splash-screen
yarn add react-native-mmkv
yarn add react-native-vector-icons
yarn add react-native-permissions
yarn add react-native-linear-gradient
yarn add react-native-skeleton-placeholder
yarn add react-native-render-html
yarn add react-native-image-crop-picker
yarn add react-native-video
yarn add react-native-restart
yarn add react-native-svg
yarn add react-native-svg-transformer
yarn add react-native-maps
yarn add react-native-dotenv
yarn add react-native-date-picker
yarn add react-native-render-html
yarn add yup
yarn add formik
yarn add axios
yarn add redux
yarn add crypto-js
yarn add i18next
yarn add react-i18next
yarn add react-redux
yarn add redux-thunk
yarn add redux-saga
yarn add immer
yarn add moment
yarn add socket.io/client
yarn add @reduxjs/toolkit
yarn add @tanstack/react-query
yarn add @react-navigation/native
yarn add @react-navigation/native-stack
yarn add @react-navigation/drawer
yarn add @react-navigation/bottom-tabs
yarn add @react-native-community/geolocation
yarn add @react-native-community/netinfo
yarn add @react-native-community/checkbox
yarn add @react-native-masked-view/masked-view
yarn add @react-native-clipboard/clipboard
yarn add @gorhom/bottom-sheet